[assembly: System.Reflection.AssemblyProduct("DynamicDescriptors")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Matthew King 2012-2013")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0")]
